const ACTIONS = {
    ADD_PROXIES : "PROXY_ADD_PROXIES",
    CLEAR_PROXIES : "PROXY_CLEAR_PROXIES",
    DELETE_PROXY : "PROXY_DELETE_PROXY",
    LOAD_PROXIES : "PROXY_LOAD_PROXIES",
    SET_PROXY_STATUS : "PROXY_SET_PROXY_STATUS",
}
export default ACTIONS;