const ACTIONS = {
    LOAD_MODELS: "MODEL.LOAD_MODELS",
    GET_MODEL_CONTENT: "MODEL.GET_MODEL_CONTENT",
    LOAD_ALL_DISCORDS: "DISCORD.LOAD_ALL_DISCORDS",
    LOAD_DISCORDS: "DISCORD.LOAD_DISCORDS",
    LOAD_ACCOUNTS: "ACCOUNT.LOAD_ACCOUNTS",
    LOAD_ACCOUNT_HISTORY: "ACCOUNT.LOAD_ACCOUNT_HISTORY",
    LOAD_ALL_MODELS: "ACCOUNT.LOAD_ALL_MODELS",
    LOAD_SCHEDULES: "POST.LOAD_POSTS",
}

export default ACTIONS;