const ACTIONS = {
  LOAD_AFFILIATES: "ADMIN.LOAD_AFFILIATES",
  LOAD_PROXIES: "ADMIN.LOAD_PROXIES",
  LOAD_AGENCY_PROXIES: "ADMIN.LOAD_AGENCY_PROXIES",
  
  LOAD_AGENCIES: "ADMIN.LOAD_AGENCIES",
  LOAD_AGENCY_LIST: "ADMIN.LOAD_AGENCY_LIST",
  
  LOAD_CHAT_TEAMS: "ADMIN.LOAD_CHAT_TEAMS",

  LOAD_ACCOUNTS: "ADMIN.LOAD_ACCOUNTS",

  LOAD_MODELS: "ADMIN.LOAD_MODELS",
}

export default ACTIONS;