const ACTIONS = {
  LOAD_AFFILIATES: "ADMIN.LOAD_AFFILIATES",
  LOAD_PROXIES: "ADMIN.LOAD_PROXIES",
  LOAD_AGENCY_PROXIES: "ADMIN.LOAD_AGENCY_PROXIES",
  LOAD_AGENCIES: "ADMIN.LOAD_AGENCIES",
}

export default ACTIONS;