const ACTIONS = {
  LOAD_PROFILE: "V2.LOAD_PROFILE",
  GET_AFFILIATE: "V2.GET_AFFILIATE",
  GET_PAYMENT: "V2.GET_PAYMENT",
  LOAD_PAYMENTS: "V2.LOAD_PAYMENTS",
  LOAD_TRANSACTIONS: "V2.LOAD_TRANSACTIONS",

  LOAD_PROXIES : "PROXY_LOAD_PROXIES",
}

export default ACTIONS;