const ACTIONS = {
  LOAD_PROFILE: "V2.LOAD_PROFILE",
  GET_AFFILIATE: "V2.GET_AFFILIATE",
  GET_PAYMENT: "V2.GET_PAYMENT",
  LOAD_PAYMENTS: "V2.LOAD_PAYMENTS",
  LOAD_TRANSACTIONS: "V2.LOAD_TRANSACTIONS",

  LOAD_PROXIES: "V2.LOAD_PROXIES",

  LOAD_MODELS: "V2.LOAD_MODELS",
  GET_MODEL_CONTENTS: "V2.GET_MODEL_CONTENTS",

  LOAD_ACCOUNTS: "V2.LOAD_ACCOUNTS",
  LOAD_ACCOUNT_HISTORY: "V2.LOAD_ACCOUNT_HISTORY",
  LOAD_ACCOUNT_LIST: "V2.LOAD_ACCOUNT_LIST",
  LOAD_MODEL_LIST: "V2.LOAD_MODEL_LIST",

  LOAD_SCHEDULE_CONTENTS: "V2.LOAD_SCHEDULE_CONTENTS",
  LOAD_SCHEDULE_RESULTS: "V2.LOAD_SCHEDULE_RESULTS",

  LOAD_CHAT_TEAMS: "V2.LOAD_CHAT_TEAMS",
  GET_STATISTICS: "V2.GET_STATISTICS",

  CHANGE_THEME: "V2.CHANGE_THEME",

  LOAD_COMMENTS: "V2.LOAD_COMMENTS",
  LOAD_BLOCK_USERS: "V2.LOAD_BLOCK_USERS",

}

export default ACTIONS;