module.exports = {
  DEFAULT_COMMENT_INTERVAL: 30,
  DEFAULT_FOLLOW_INTERVAL: 30,
  DEFAULT_CHAT_INTERVAL: 10,

  DEFAULT_STORY_INTERVAL: 30,
  DEFAULT_STORY_OFFSETS: [1, 21, 51],

  DEFAULT_POST_INTERVAL: 60,
  DEFAULT_POST_OFFSETS: [1, 21, 51],
};