const ACTIONS = {
    LOAD_STATS : "DASHBOARD.LOAD_ACTIONS",
    LOAD_SETTING: "DASHBOARD.LOAD_SETTING",
    UPDATE_SETTING: "DASHBOARD.UPDATE_SETTING",
    LOAD_MANAGERS : "DASHBOARD.LOAD_MANAGERS",
    CHANGE_PASSWORD : "DASHBOARD.CHANGE_PASSWORD",
    LOGIN_MANAGER : "DASHBOARD.LOGIN_MANAGER",
    RELOAD_MANAGER : "DASHBOARD.RELOAD_MANAGER",
    LOGOUT_MANAGER : "DASHBOARD.LOGOUT_MANAGER",
    LOAD_COMMENTS : "COMMENT.LOAD_COMMENTS",
    UPDATE_COMMENTS : "COMMENT.UPDATE_COMMENTS",
    LOAD_USERS : "USER.LOAD_USERS",
    UPDATE_USERS : "USER.UPDATE_USERS",
};

export default ACTIONS;